[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
nvml-wrapper = "0.8"
async-nats = "0.38"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
